from wtforms import ValidationError


def allowed_values(values):
    """
    Function for splitting the allowed values into 'or' separated string.
    @param values: Set of allowed possible values.
    @return: A string generated by concatenating values - separated by or.
    """
    values_str = ' or '.join(map(str, values))
    return values_str


def validate_complaint_list(form, field):
    """
    Checking whether the list of garments for complaint has mandatory fields or not.
    @param form:
    @param field:
    @return: If validation fails, validator will return a validation error.
    """
    complaint_list = field.data
    valid = True
    for complaint in complaint_list:
        if complaint.get('complaint_id') is None:
            valid = False
            break
        if complaint.get('branch_code') is None:
            valid = False
            break
        if complaint.get('remarks') is None:
            valid = True
            break
        if complaint.get('yes_or_no') is None:
            valid = True
            break
        if complaint.get('b64_image') is None:
            valid = True
            break
        if complaint.get('file') is None:
            valid = True
            break
    if not valid:
        raise ValidationError(
            'complaint_id, branch_code, remarks, b64_image,yes_or_no, file are required in the complaint_list.')


def validate_tag_list(form, field):
    """
    Checking whether the list of tags has mandatory fields or not.
    @param form:
    @param field:
    @return: If validation fails, validator will return a validation error.
    """
    tag_list = field.data
    valid = True
    for tag in tag_list:
        if tag.get('entry_type') is None:
            valid = False
            break
        if tag.get('tag_no') is None:
            valid = False
            break

    if not valid:
        raise ValidationError(
            'entry_type, tag_no are required in the tag_list.')


def validate_audit_updates_list(form, field):
    """
    Checking whether the list of audit updates has mandatory fields or not.
    @param form:
    @param field:
    @return: If validation fails, validator will return a validation error.
    """
    audit_updates_list = field.data
    valid = True
    for audit in audit_updates_list:
        if audit.get('WithoutComplaintsCount') is None:
            valid = False
            break
        if audit.get('WithComplaintsCount') is None:
            valid = False
            break
        if audit.get('OtherStoresCount') is None:
            valid = True
            break
        if audit.get('TotalGarmentCount') is None:
            valid = True
            break
        if audit.get('TotalTagsScanned') is None:
            valid = True
            break
        if audit.get('NoStock') is None:
            valid = True
            break
        if audit.get('ScannedDate') is None:
            valid = True
            break
        if audit.get('ScannedBy') is None:
            valid = True
            break
        if audit.get('InLocation') is None:
            valid = True
            break
        if audit.get('Store') is None:
            valid = True
            break
    if not valid:
        raise ValidationError(
            'complaint_id, branch_code, remarks, b64_image,yes_or_no are required in the complaint_list.')


def validate_audit_summary_list(form, field):
    """
    Checking whether the list of audit summary details has mandatory fields or not.
    @param form:
    @param field:
    @return: If validation fails, validator will return a validation error.
    """
    audit_updates_list = field.data
    valid = True
    for audit in audit_updates_list:
        if audit.get('WithoutComplaintsCount') is None:
            valid = False
            break
        if audit.get('WithComplaintsCount') is None:
            valid = False
            break
        if audit.get('OtherStoresCount') is None:
            valid = True
            break
        if audit.get('TotalGarmentCount') is None:
            valid = True
            break
        if audit.get('WithComplaints') is None:
            valid = True
            break
        if audit.get('WithoutComplaints') is None:
            valid = True
            break
        if audit.get('OtherStores') is None:
            valid = True
            break
        if audit.get('ScannedDate') is None:
            valid = True
            break
        if audit.get('ScannedBy') is None:
            valid = True
            break
        if audit.get('InLocation') is None:
            valid = True
            break
        if audit.get('Store') is None:
            valid = True
            break
    if not valid:
        raise ValidationError(
            'complaint_id, branch_code, remarks, b64_image,yes_or_no are required in the complaint_list.')


def validate_audit_detailed_list(form, field):
    """
    Checking whether the list of audit summary details has mandatory fields or not.
    @param form:
    @param field:
    @return: If validation fails, validator will return a validation error.
    """
    audit_updates_list = field.data
    valid = True
    for audit in audit_updates_list:
        if audit.get('WithoutComplaintsCount') is None:
            valid = False
            break
        if audit.get('WithComplaintsCount') is None:
            valid = False
            break
        if audit.get('OtherStoresCount') is None:
            valid = True
            break
        if audit.get('TotalGarmentCount') is None:
            valid = True
            break
        if audit.get('WithComplaints') is None:
            valid = True
            break
        if audit.get('WithoutComplaints') is None:
            valid = True
            break
        if audit.get('OtherStores') is None:
            valid = True
            break
        if audit.get('ScannedDate') is None:
            valid = True
            break
        if audit.get('ScannedBy') is None:
            valid = True
            break
        if audit.get('InLocation') is None:
            valid = True
            break
        if audit.get('Store') is None:
            valid = True
            break
    if not valid:
        raise ValidationError(
            'complaint_id, branch_code, remarks, b64_image,yes_or_no are required in the complaint_list.')
def validate_garment_audit_updates_list(form, field):
    """
    audit_updates_list
    Checking whether the list of audit updates has mandatory fields or not.
    @param form:
    @param field:
    @return: If validation fails, validator will return a validation error.
    """
    garment_audit_updates_list = field.data
    valid = True
    for audit in garment_audit_updates_list:
        if audit.get('audit_date') is None:
            valid = False
            break
        if audit.get('is_mss') is None:
            valid = False
            break
        if audit.get('ScanId') is None:
            valid = True
            break
        if audit.get('branch_code') is None:
            valid = True
            break
        if audit.get('branch_name') is None:
            valid = True
            break
        if audit.get('InLocation') is None:
            valid = True
            break
        if audit.get('mss_list') is None:
            valid = True
            break
        if audit.get('other_store_list') is None:
            valid = True
            break

    if not valid:
        raise ValidationError(
            'audit_date, ScanId, mss_list are required in the list.')
