from wtforms import ValidationError
import re
from dcr import db
# from dcr.modules.models import Customer, Order

def allowed_values(values):
    """
    Function for splitting the allowed values into 'or' separated string.
    @param values: Set of allowed possible values.
    @return: A string generated by concatenating values - separated by or.
    """
    values_str = ' or '.join(map(str, values))
    return values_str

def validate_complaint_list(form, field):
    """
    Checking whether the list of garments for complaint has mandatory fields or not.
    @param form:
    @param field:
    @return: If validation fails, validator will return a validation error.
    """
    complaint_list = field.data
    valid = True
    for complaint in complaint_list:
        if complaint.get('complaint_id') is None:
            valid = False
            break
        if complaint.get('branch_code') is None:
            valid = False
            break
        if complaint.get('remarks') is None:
            valid = True
            break
        if complaint.get('b64_image') is None:
            valid = True
            break
    if not valid:
        raise ValidationError(
            'complaint_id, branch_code are required in the complaint_list.')
